default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: user
  password: password
  host: db

development:
  <<: *default
  database: database_development
  url: <%= ENV["DATABASE_URL"] %>

test:
  <<: *default
  database: nightmare_app_test

production:
  <<: *default
  database: nightmare_app_backend_production
  username: nightmare_app_backend
  password: <%= ENV["NIGHTMARE_APP_BACKEND_DATABASE_PASSWORD"] %>
