default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: database_development
  username: user
  password: password
  host: db

test:
  <<: *default
  database: nightmare_app_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
